; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
build_flags =
    -Icomponents/tensorflow
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
    -DTF_LITE_STRIP_ERROR_STRINGS
    -DTF_LITE_STRIP_LOGGING
    -DTF_LITE_DISABLE_X86_SIMD

build_unflags = 
    -O2

board_build.psram = enabled

board_build.flash_size = 8MB
board_build.partitions = partitions_ota_8mb.csv